name: Deploy Terraform Configuration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.1.0"

    - name: Configure Azure Credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: |
        terraform plan -var-file="${{ secrets.TF_VARS_FILE }}" -out=tfplan \
        -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
        -var="ngc_api_key=${{ secrets.NGC_API_KEY }}" \
        -var="ngc_email=${{ secrets.NGC_EMAIL }}" \
        -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
        -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
        -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
        -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"

    - name: Terraform Apply
      run: terraform apply "tfplan"

    - name: Azure Logout
      run: az logout
