# This is a basic workflow to help you get started with Actions

name: AZAKSCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.7.0"

      - name: Configure Azure Credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: List files in Terraform directory
        run: ls -l

      - name: Display non-sensitive content of the tfvars file
        run: cat terraform/terraform.tfvars
              
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID}}” \
            -backend-config="resource_group_name=${{ secrets.AZURE_RESOURCE_GROUP }}" \
            -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ secrets.AZURE_CONTAINER }}" \
            -backend-config="key=terraform.tfstate”

      - name: Terraform Plan
        run: |
          terraform plan -var-file="terraform/terraform.tfvars" -out=tfplan \
          -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
          -var="ngc_api_key=${{ secrets.NGC_API_KEY }}" \
          -var="ngc_email=${{ secrets.NGC_EMAIL }}" \
          -var="provider_config={ \
            tenant_id='${{ secrets.AZURE_TENANT_ID }}', \
            subscription_id='${{ secrets.AZURE_SUBSCRIPTION_ID }}', \
            client_id='${{ secrets.AZURE_CLIENT_ID }}', \
            client_secret='${{ secrets.AZURE_CLIENT_SECRET }}' \
          }"

      - name: Terraform Apply
        run: terraform apply "tfplan"

      - name: Azure Logout
        run: az logout
